apiVersion: v1
kind: Service
metadata:
  name: {{ include "amazon-ecr-repository-compliance-webhook.fullname" . }}
  labels:
    {{- include "amazon-ecr-repository-compliance-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "amazon-ecr-repository-compliance-webhook.selectorLabels" . | nindent 4 }}
