{{- if .Values.ValidatingWebhookConfiguration.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "amazon-ecr-repository-compliance-webhook.fullname" . }}
  labels:
    {{- include "amazon-ecr-repository-compliance-webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    name: admission.ecr.amazonaws.com
    timeoutSeconds: 10
    sideEffects: None
    failurePolicy: Fail # v1beta1 default is Ignore
    clientConfig:
      url: {{ .Values.webhookUrl }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]


    # namespaceSelector: # Optionally add a namespaceSelector and matchLabels
    #   matchLabels:
    #     amazon-ecr-repository-compliance-webhook: enabled
{{- end }}