serviceAccount:
  name: "amazon-ecr-repository-compliance-webhook"

httpRoute:
  enabled: true
  annotations: {}
  gateway:
    name: external
    namespace: istio-ingress
  hosts:
    - repository-compliance-webhook.webinar.external.blackbird.cloud

webhookUrl: https://repository-compliance-webhook.webinar.external.blackbird.cloud
